// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cardex/auction/auction.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Auction struct {
	AuctionID       string `protobuf:"bytes,1,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	MinimumBid      string `protobuf:"bytes,2,opt,name=minimumBid,proto3" json:"minimumBid,omitempty"`
	Bid             string `protobuf:"bytes,3,opt,name=bid,proto3" json:"bid,omitempty"`
	AuctionDuration string `protobuf:"bytes,4,opt,name=auctionDuration,proto3" json:"auctionDuration,omitempty"`
	CarDescription  string `protobuf:"bytes,5,opt,name=carDescription,proto3" json:"carDescription,omitempty"`
	CarPictureUrl   string `protobuf:"bytes,6,opt,name=carPictureUrl,proto3" json:"carPictureUrl,omitempty"`
	Status          string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Creator         string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Auction) Reset()         { *m = Auction{} }
func (m *Auction) String() string { return proto.CompactTextString(m) }
func (*Auction) ProtoMessage()    {}
func (*Auction) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9b83f3ab0d4109, []int{0}
}
func (m *Auction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Auction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Auction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Auction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auction.Merge(m, src)
}
func (m *Auction) XXX_Size() int {
	return m.Size()
}
func (m *Auction) XXX_DiscardUnknown() {
	xxx_messageInfo_Auction.DiscardUnknown(m)
}

var xxx_messageInfo_Auction proto.InternalMessageInfo

func (m *Auction) GetAuctionID() string {
	if m != nil {
		return m.AuctionID
	}
	return ""
}

func (m *Auction) GetMinimumBid() string {
	if m != nil {
		return m.MinimumBid
	}
	return ""
}

func (m *Auction) GetBid() string {
	if m != nil {
		return m.Bid
	}
	return ""
}

func (m *Auction) GetAuctionDuration() string {
	if m != nil {
		return m.AuctionDuration
	}
	return ""
}

func (m *Auction) GetCarDescription() string {
	if m != nil {
		return m.CarDescription
	}
	return ""
}

func (m *Auction) GetCarPictureUrl() string {
	if m != nil {
		return m.CarPictureUrl
	}
	return ""
}

func (m *Auction) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Auction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Auction)(nil), "uwezukwechibuzor.cardex.auction.Auction")
}

func init() { proto.RegisterFile("cardex/auction/auction.proto", fileDescriptor_9c9b83f3ab0d4109) }

var fileDescriptor_9c9b83f3ab0d4109 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0x56, 0x13, 0x3b, 0xe0, 0x1f, 0xf6, 0x20, 0x7b, 0x28, 0xab, 0x88, 0x48, 0x4f,
	0x09, 0xe8, 0x13, 0x58, 0x72, 0x11, 0x3c, 0x88, 0xe0, 0xc5, 0xdb, 0x66, 0xb3, 0xd8, 0x45, 0xd3,
	0x0d, 0x93, 0x5d, 0x5a, 0x7b, 0xf5, 0x05, 0x7c, 0x2c, 0x8f, 0x3d, 0x7a, 0x94, 0xe4, 0x45, 0xa4,
	0xd3, 0x94, 0x6a, 0x4e, 0x33, 0xf3, 0xfb, 0x7e, 0x0b, 0xcb, 0x07, 0x23, 0x25, 0x31, 0xd7, 0x8b,
	0x44, 0x7a, 0xe5, 0x8c, 0x9d, 0x6d, 0x67, 0x5c, 0xa2, 0x75, 0x96, 0x9d, 0xf9, 0xb9, 0x5e, 0xfa,
	0xd7, 0xb9, 0x56, 0x53, 0x93, 0xf9, 0xa5, 0xc5, 0x78, 0xa3, 0xc7, 0xad, 0x76, 0xf1, 0xd1, 0x87,
	0xe8, 0x76, 0xb3, 0xb3, 0x11, 0x0c, 0x5b, 0x7c, 0x97, 0xf2, 0xe0, 0x3c, 0x18, 0x0f, 0x1f, 0x77,
	0x80, 0x09, 0x80, 0xc2, 0xcc, 0x4c, 0xe1, 0x8b, 0x89, 0xc9, 0x79, 0x9f, 0xe2, 0x3f, 0x84, 0x9d,
	0xc0, 0x20, 0x33, 0x39, 0x1f, 0x50, 0xb0, 0x5e, 0xd9, 0x18, 0x8e, 0xdb, 0xe7, 0xa9, 0x47, 0xb9,
	0x9e, 0x7c, 0x8f, 0xd2, 0x2e, 0x66, 0x57, 0x70, 0xa4, 0x24, 0xa6, 0xba, 0x52, 0x68, 0x4a, 0x12,
	0xf7, 0x49, 0xec, 0x50, 0x76, 0x09, 0x87, 0x4a, 0xe2, 0x83, 0x51, 0xce, 0xa3, 0x7e, 0xc2, 0x37,
	0x1e, 0x92, 0xf6, 0x1f, 0xb2, 0x53, 0x08, 0x2b, 0x27, 0x9d, 0xaf, 0x78, 0x44, 0x71, 0x7b, 0x31,
	0x0e, 0x91, 0x42, 0x2d, 0x9d, 0x45, 0x7e, 0x40, 0xc1, 0xf6, 0x9c, 0xdc, 0x7f, 0xd5, 0x22, 0x58,
	0xd5, 0x22, 0xf8, 0xa9, 0x45, 0xf0, 0xd9, 0x88, 0xde, 0xaa, 0x11, 0xbd, 0xef, 0x46, 0xf4, 0x9e,
	0xaf, 0x5f, 0x8c, 0x9b, 0xfa, 0x2c, 0x56, 0xb6, 0x48, 0xba, 0x5d, 0x26, 0xf4, 0xbb, 0x45, 0xb2,
	0x2b, 0xdf, 0xbd, 0x97, 0xba, 0xca, 0x42, 0xea, 0xfe, 0xe6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x14,
	0x0f, 0x11, 0x20, 0x9b, 0x01, 0x00, 0x00,
}

func (m *Auction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Auction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Auction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CarPictureUrl) > 0 {
		i -= len(m.CarPictureUrl)
		copy(dAtA[i:], m.CarPictureUrl)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.CarPictureUrl)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CarDescription) > 0 {
		i -= len(m.CarDescription)
		copy(dAtA[i:], m.CarDescription)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.CarDescription)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AuctionDuration) > 0 {
		i -= len(m.AuctionDuration)
		copy(dAtA[i:], m.AuctionDuration)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.AuctionDuration)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Bid) > 0 {
		i -= len(m.Bid)
		copy(dAtA[i:], m.Bid)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.Bid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MinimumBid) > 0 {
		i -= len(m.MinimumBid)
		copy(dAtA[i:], m.MinimumBid)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.MinimumBid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuctionID) > 0 {
		i -= len(m.AuctionID)
		copy(dAtA[i:], m.AuctionID)
		i = encodeVarintAuction(dAtA, i, uint64(len(m.AuctionID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuction(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Auction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuctionID)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	l = len(m.MinimumBid)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	l = len(m.Bid)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	l = len(m.AuctionDuration)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	l = len(m.CarDescription)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	l = len(m.CarPictureUrl)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAuction(uint64(l))
	}
	return n
}

func sovAuction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuction(x uint64) (n int) {
	return sovAuction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Auction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Auction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Auction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumBid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinimumBid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionDuration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionDuration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CarDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CarDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CarPictureUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CarPictureUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuction = fmt.Errorf("proto: unexpected end of group")
)
